# Copyright 2024 AshScylla Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defmodule Mix.Tasks.AshScylla.GenerateMigrations do
  @moduledoc """
  Generates CQL migration files from Ash resource definitions, and stores snapshots.

  This task compares current Ash resource definitions against stored snapshots
  (and optionally the live database schema) to determine what DDL changes are
  needed, then generates a migration file with the appropriate CQL statements.

  ## Usage

      # Generate migrations for all resources
      mix ash_scylla.generate_migrations

      # Generate with a specific name
      mix ash_scylla.generate_migrations add_user_table

      # Dry run (print without creating files)
      mix ash_scylla.generate_migrations --dry-run

      # Check if migrations are needed (exit code 1 if so)
      mix ash_scylla.generate_migrations --check

      # Only update snapshots, don't generate migration files
      mix ash_scylla.generate_migrations --snapshots-only

      # Dev mode (auto-name with _dev suffix)
      mix ash_scylla.generate_migrations --dev

  ## Options

    - `--domains` - comma-separated list of domain modules to generate for
    - `--snapshot-path` - custom path for snapshots (default: `priv/repo/resource_snapshots`)
    - `--migration-path` - custom path for migrations (default: `priv/repo/migrations`)
    - `--name` - name for the migration file (auto-generated by default)
    - `--quiet` - suppress file creation messages
    - `--no-format` - don't format the generated Elixir code
    - `--dry-run` - print migrations without creating files
    - `--check` - return exit code 1 if migrations are needed
    - `--dev` - create dev migrations (suffixed with `_dev`)
    - `--snapshots-only` - only create snapshots, no migration files

  ## Snapshots

  Snapshots are JSON files stored in `priv/<repo>/resource_snapshots/` that
  capture the schema state of each resource at a point in time. The generator
  compares the current resource definition against the most recent snapshot
  to determine what changes need to be made.

  ## Generated Migration Format

  Generated migrations use `AshScylla.Schema` and contain CQL statements:

      defmodule MyApp.Migrations.MigrateResources1 do
        @moduledoc \"\"\"
        Migration for users.

        This file was autogenerated with `mix ash_scylla.generate_migrations`
        \"\"\"

        use AshScylla.Schema

        @impl AshScylla.Schema
        def change do
          [
            "CREATE TABLE IF NOT EXISTS \"users\" (id UUID PRIMARY KEY, name TEXT)",
            "CREATE INDEX IF NOT EXISTS idx_users_email ON \"users\" (email)"
          ]
        end
      end
  """

  use Mix.Task

  @shortdoc "Generates CQL migration files from Ash resource definitions"

  @impl Mix.Task
  def run(args) do
    {name, args} =
      case args do
        ["-" <> _ | _] ->
          {nil, args}

        [first | rest] ->
          {first, rest}

        [] ->
          {nil, []}
      end

    {opts, _} =
      OptionParser.parse!(args,
        strict: [
          domains: :string,
          snapshot_path: :string,
          migration_path: :string,
          quiet: :boolean,
          name: :string,
          no_format: :boolean,
          dry_run: :boolean,
          check: :boolean,
          dev: :boolean,
          snapshots_only: :boolean
        ]
      )

    domains = parse_domains(opts)

    opts =
      opts
      |> Keyword.put(:format, !opts[:no_format])
      |> Keyword.delete(:no_format)
      |> Keyword.put_new(:name, name)
      |> Keyword.put(:domains, domains)

    AshScylla.MigrationGenerator.generate(opts)
  end

  defp parse_domains(opts) do
    case Keyword.get(opts, :domains) do
      nil ->
        []

      domains_str ->
        domains_str
        |> String.split(",")
        |> Enum.map(&String.trim/1)
        |> Enum.reject(&(&1 == ""))
        |> Enum.map(&Module.concat([&1]))
    end
  end
end
