# Copyright [2024] AshScylla Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defmodule Mix.Tasks.AshScylla.Gen do
  @moduledoc """
  Generates a schema migration file from Ash DSL resource definitions.

  Scans the project for Ash resources using `AshScylla.DataLayer` and produces
  a `priv/migrations/<timestamp>_<name>.ex` file containing `CREATE TABLE` and
  `CREATE INDEX` CQL statements derived from each resource's attributes and
  secondary indexes.

  ## Usage

      # Auto-generate schema file with timestamp-based name
      mix ash_scylla.gen --dev

      # Generate with a specific schema module name
      mix ash_scylla.gen AddUserTable

      # Generate for a specific resource only
      mix ash_scylla.gen --resource MyApp.User

  ## Options

  - `--dev` — auto-name the schema file (timestamp-based). If no name argument
    is given, `--dev` is assumed.
  - `--resource` — only generate schema for the given resource module.

  ## Output

  Generated files go to `priv/migrations/` and use `AshScylla.Schema`:

      defmodule MyApp.Migrations.AddUserTable do
        @moduledoc \"\"\"
        Schema migration generated by `mix ash_scylla.gen`.
        \"\"\"

        use AshScylla.Schema

        @impl AshScylla.Schema
        def change do
          [
            "CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, name TEXT, email TEXT)",
            "CREATE INDEX IF NOT EXISTS idx_users_email ON users (email)"
          ]
        end
      end

  Run migrations with: `mix ash_scylla.migrate`
  """

  @shortdoc "Generates schema migration files from Ash DSL"

  @requirements ["app.start"]

  use Mix.Task

  @impl Mix.Task
  def run(args) do
    {opts, remaining} = parse_cli_opts(args)

    resources = find_resources(opts)

    if resources == [] do
      apps = AshScylla.MixHelpers.project_apps()
      domains = AshScylla.MixHelpers.project_domains()

      Mix.shell().info("""
      No AshScylla resources found.

      To fix this, ensure your project has:

      1. Ash domains configured in config:
         config :your_app, ash_domains: [YourApp.YourDomain]

      2. Resources using AshScylla.DataLayer:
         use Ash.Resource,
           data_layer: AshScylla.DataLayer

      3. Or generate a resource:
         mix ash_scylla.gen --resource YourApp.YourDomain.YourResource

      Apps inspected: #{inspect(apps)}
      Domains found: #{inspect(domains)}
      """)
    else
      schema_name = schema_module_name(remaining, opts)
      write_schema_migration(schema_name, resources)
    end
  end

  defp parse_cli_opts(args) do
    {opts, remaining} =
      OptionParser.parse!(args,
        strict: [dev: :boolean, resource: :string],
        aliases: [d: :dev]
      )

    opts = opts |> AshScylla.MixHelpers.maybe_atomize(:resource)

    {opts, remaining}
  end

  defp find_resources(opts) do
    case Keyword.get(opts, :resource) do
      nil -> AshScylla.MixHelpers.find_all_resources()
      resource -> [resource]
    end
  end

  # Determine the schema module name.
  # "mix ash_scylla.gen --dev"        -> auto-name from resources
  # "mix ash_scylla.gen AddUserTable" -> use the given name
  defp schema_module_name([], _opts) do
    timestamp = DateTime.utc_now() |> Calendar.strftime("%Y%m%d%H%M%S")
    String.to_atom("Schema#{timestamp}")
  end

  defp schema_module_name([name | _], _opts) do
    case String.length(name) do
      0 -> Mix.raise("Schema module name cannot be empty")
      _ -> String.to_atom(name)
    end
  end

  defp write_schema_migration(schema_name, resources) do
    app = AshScylla.MixHelpers.app_name()
    app_module = app |> Atom.to_string() |> Macro.camelize() |> String.to_atom()
    module_name = Module.concat([app_module, :Migrations, schema_name])
    file_path = Path.join("priv/migrations", Macro.underscore(to_string(schema_name)) <> ".ex")

    all_statements =
      Enum.flat_map(resources, fn resource ->
        table_name = resource |> Module.split() |> List.last() |> Macro.underscore()
        attributes = Ash.Resource.Info.attributes(resource)
        indexes = AshScylla.DataLayer.Dsl.secondary_indexes(resource)
        render_resource_statements(table_name, attributes, indexes)
      end)

    content = render_schema_module(module_name, all_statements)

    File.mkdir_p!(Path.dirname(file_path))
    File.write!(file_path, content)

    Mix.shell().info("Generated schema migration #{file_path}")
    Mix.shell().info("  Resources: #{length(resources)}")
    Mix.shell().info("  Statements: #{length(all_statements)}")
    Mix.shell().info("Run with: mix ash_scylla.migrate")
  end

  defp render_resource_statements(table_name, attributes, indexes) do
    table_cql = render_create_table_cql(table_name, attributes)
    index_cqls = render_index_cqls(table_name, indexes)
    [table_cql | index_cqls]
  end

  defp render_create_table_cql(table_name, attributes) do
    columns =
      attributes
      |> Enum.reject(fn attr -> attr.name == :id end)
      |> Enum.map_join(", ", fn attr ->
        type_str = AshScylla.Migration.ash_type_to_cql_type(attr.type, attr.constraints)
        "#{attr.name} #{type_str}"
      end)

    "CREATE TABLE IF NOT EXISTS #{table_name} (id UUID PRIMARY KEY, #{columns})"
  end

  defp render_index_cqls(_table_name, []), do: []

  defp render_index_cqls(table_name, indexes) do
    Enum.map(indexes, fn idx ->
      index_name = idx.name || generate_index_name(table_name, idx.columns)
      columns = idx.columns |> Enum.map_join(", ", &to_string/1)
      "CREATE INDEX IF NOT EXISTS #{index_name} ON #{table_name} (#{columns})"
    end)
  end

  defp generate_index_name(table_name, columns) do
    column_str = columns |> Enum.map_join("_", &to_string/1)
    "idx_#{table_name}_#{column_str}"
  end

  defp render_schema_module(module_name, cql_statements) do
    statements_literal =
      cql_statements
      |> Enum.map(&"    \"#{&1}\"")
      |> Enum.join(",\n")

    """
    defmodule #{module_name} do
      @moduledoc \"\"\"
      Schema migration generated by `mix ash_scylla.gen`.
      \"\"\"

      use AshScylla.Schema

      @impl AshScylla.Schema
      def change do
    [
    #{statements_literal}
    ]
      end
    end
    """
  end

end
