# Copyright [2024] AshScylla Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defmodule Mix.Tasks.AshScylla.Gen do
  @moduledoc """
  Generates a schema migration file from Ash DSL resource definitions.

  Scans the project for Ash resources using `AshScylla.DataLayer` and produces
  a `priv/migrations/<timestamp>_<name>.ex` file containing structured
  `%AshScylla.Schema{}` entries organised by domain and resource.

  > #### Deprecation {: .warning}
  >
  > This task is deprecated in favor of `mix ash_scylla.generate_migrations`,
  > which provides snapshot-based migration generation with proper diffing.
  > Use `mix ash_scylla.generate_migrations` for new projects.

  ## Usage

      # Auto-generate schema file with timestamp-based name
      mix ash_scylla.gen --dev

      # Generate with a specific schema module name
      mix ash_scylla.gen AddUserTable

      # Generate for a specific resource only
      mix ash_scylla.gen --resource MyApp.User

  ## Options

  - `--dev` — auto-name the schema file (timestamp-based). If no name argument
    is given, `--dev` is assumed.
  - `--resource` — only generate schema for the given resource module.
  - `--force` — force regeneration even if no schema changes detected.

  ## Output

  Generated files go to `priv/migrations/` and use `AshScylla.Schema` with
  a struct-based format that groups resources by domain:

      defmodule MyApp.Migrations.Schema20260615155440 do
        @moduledoc ""
        Schema migration generated by `mix ash_scylla.gen`.
        ""

        use AshScylla.Schema

        @impl AshScylla.Schema
        def change do
          [
            %AshScylla.Schema{
              domain: MyApp.Domain,
              resources: [
                %AshScylla.Schema.Resource{
                  name: :users,
                  statements: [
                    "CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, name TEXT, email TEXT)",
                    "CREATE INDEX IF NOT EXISTS idx_users_email ON users (email)"
                  ]
                }
              ]
            }
          ]
        end
      end

  Run migrations with: `mix ash_scylla.migrate`
  """

  @shortdoc "Generates schema migration files from Ash DSL"

  @requirements ["app.start"]

  use Mix.Task

  @impl Mix.Task
  def run(args) do
    {opts, remaining} = parse_cli_opts(args)

    resources = find_resources(opts)

    if resources == [] do
      apps = AshScylla.MixHelpers.project_apps()
      domains = AshScylla.MixHelpers.project_domains()

      Mix.shell().info("""
      No AshScylla resources found.

      To fix this, ensure your project has:

      1. Ash domains configured in config:
         config :your_app, ash_domains: [YourApp.YourDomain]

      2. Resources using AshScylla.DataLayer:
         use Ash.Resource,
           data_layer: AshScylla.DataLayer

      3. Or generate a resource:
         mix ash_scylla.gen --resource YourApp.YourDomain.YourResource

      Apps inspected: #{inspect(apps)}
      Domains found: #{inspect(domains)}
      """)
    else
      maybe_generate_migration(resources, remaining, opts)
    end
  end

  # Checks if any resource schema has changed since the last generation.
  # If nothing changed, reports "up to date". Otherwise generates a new
  # migration file containing only the changed resources.
  #
  # Uses the same `.schema_meta` file as `mix ash.codegen` so both commands
  # share change detection state.
  defp maybe_generate_migration(resources, remaining, opts) do
    force? = Keyword.get(opts, :force, false)
    meta_file = schema_meta_path()
    previous_meta = AshScylla.DataLayer.load_codegen_meta(meta_file)

    changed_resources =
      if force? do
        resources
      else
        AshScylla.DataLayer.filter_changed_resources(resources, previous_meta)
      end

    if changed_resources == [] do
      Mix.shell().info("Schema is up to date. No changes detected.")
    else
      current_meta = AshScylla.DataLayer.compute_codegen_meta(resources)

      AshScylla.DataLayer.save_codegen_meta(
        meta_file,
        AshScylla.DataLayer.merge_codegen_meta(previous_meta, changed_resources, current_meta)
      )

      schema_name = schema_module_name(remaining, opts)
      write_schema_migration(schema_name, changed_resources)

      unchanged = length(resources) - length(changed_resources)

      if force? do
        Mix.shell().info("  Forced regeneration of #{length(resources)} resource(s)")
      else
        Mix.shell().info(
          "  #{length(changed_resources)} resource(s) changed, #{unchanged} unchanged"
        )
      end
    end
  end

  # Returns the absolute path to the schema meta file in the user's project root.
  # Uses File.cwd!() to ensure we always read/write from the project where mix
  # was invoked, not from the library's own directory.
  #
  # Uses the same `.schema_meta` filename and repo-based path as `mix ash.codegen`
  # so both commands share change detection state.
  defp schema_meta_path do
    Path.join(migrations_path(), ".schema_meta")
  end

  defp migrations_path do
    repo = AshScylla.MixHelpers.find_default_repo()
    repo_name = repo |> Module.split() |> List.last() |> Macro.underscore()
    Path.join(File.cwd!(), "priv/#{repo_name}/migrations")
  rescue
    _ -> Path.join(File.cwd!(), "priv/repo/migrations")
  end

  defp parse_cli_opts(args) do
    {opts, remaining} =
      OptionParser.parse!(args,
        strict: [dev: :boolean, resource: :string, force: :boolean],
        aliases: [d: :dev]
      )

    opts = opts |> AshScylla.MixHelpers.maybe_atomize(:resource)

    # --force is consumed here, not passed to schema_module_name
    {opts, remaining}
  end

  defp find_resources(opts) do
    case Keyword.get(opts, :resource) do
      nil -> AshScylla.MixHelpers.find_all_resources()
      resource -> [resource]
    end
  end

  # Determine the schema module name.
  # "mix ash_scylla.gen --dev"        -> auto-name from resources
  # "mix ash_scylla.gen AddUserTable" -> use the given name
  defp schema_module_name([], _opts) do
    timestamp = DateTime.utc_now() |> Calendar.strftime("%Y%m%d%H%M%S")
    String.to_atom("Schema#{timestamp}")
  end

  defp schema_module_name([name | _], _opts) do
    case String.length(name) do
      0 -> Mix.raise("Schema module name cannot be empty")
      _ -> String.to_atom(name)
    end
  end

  defp write_schema_migration(schema_name, resources) do
    app = AshScylla.MixHelpers.app_name()
    app_module = app |> Atom.to_string() |> Macro.camelize() |> String.to_atom()
    module_name = Module.concat([app_module, :Migrations, schema_name])

    file_path =
      Path.join([
        migrations_path(),
        Macro.underscore(to_string(schema_name)) <> ".ex"
      ])

    # Group resources by domain
    domain_groups =
      resources
      |> Enum.group_by(fn resource ->
        try do
          case Ash.Resource.Info.domain(resource) do
            nil -> :default
            domain -> domain
          end
        rescue
          _ -> :default
        end
      end)

    content = render_schema_module(module_name, domain_groups)

    File.mkdir_p!(Path.dirname(file_path))
    File.write!(file_path, content)

    total_statements =
      Enum.reduce(domain_groups, 0, fn {_, res_list}, acc ->
        acc +
          Enum.reduce(res_list, 0, fn r, a ->
            a + length(render_resource_cql(r))
          end)
      end)

    Mix.shell().info("Generated schema migration #{file_path}")
    Mix.shell().info("  Domains: #{map_size(domain_groups)}")
    Mix.shell().info("  Resources: #{length(resources)}")
    Mix.shell().info("  Statements: #{total_statements}")
    Mix.shell().info("Run with: mix ash_scylla.migrate")
  end

  # Render CQL statements for a single resource (used for counting)
  defp render_resource_cql(resource) do
    table_name = resolve_table_name(resource)
    attributes = Ash.Resource.Info.attributes(resource)
    indexes = AshScylla.DataLayer.Dsl.secondary_indexes(resource)
    render_resource_statements(table_name, attributes, indexes)
  end

  defp render_resource_statements(table_name, attributes, indexes) do
    table_cql = render_create_table_cql(table_name, attributes)
    index_cqls = render_index_cqls(table_name, indexes)
    [table_cql | index_cqls]
  end

  defp resolve_table_name(resource) do
    table = AshScylla.DataLayer.SchemaUtils.get_table_name(resource)

    case AshScylla.DataLayer.Dsl.keyspace(resource) do
      nil ->
        table

      keyspace ->
        "#{keyspace}.#{table}"
    end
  end

  defp render_create_table_cql(table_name, attributes) do
    {pk_attrs, regular_attrs} =
      Enum.split_with(attributes, fn attr -> attr.primary_key? end)

    # If no primary key declared, fall back to :id
    {pk_attrs, regular_attrs} =
      if pk_attrs == [] do
        {id_attr, rest} = Enum.split_with(regular_attrs, fn attr -> attr.name == :id end)

        case id_attr do
          [id] -> {[id], rest}
          [] -> {[], regular_attrs}
        end
      else
        {pk_attrs, regular_attrs}
      end

    pk_columns =
      pk_attrs
      |> Enum.map(fn attr ->
        type_str = AshScylla.Migration.ash_type_to_cql_type(attr.type, attr.constraints)
        "#{AshScylla.Identifier.quote_name(attr.name)} #{type_str}"
      end)

    regular_columns =
      regular_attrs
      |> Enum.map(fn attr ->
        type_str = AshScylla.Migration.ash_type_to_cql_type(attr.type, attr.constraints)
        "#{AshScylla.Identifier.quote_name(attr.name)} #{type_str}"
      end)

    pk_clause =
      case pk_attrs do
        [single_pk] ->
          "PRIMARY KEY (#{AshScylla.Identifier.quote_name(single_pk.name)})"

        [partition_key | clustering_keys] ->
          pk_cols = [partition_key.name | Enum.map(clustering_keys, & &1.name)]
          "PRIMARY KEY (#{Enum.map_join(pk_cols, ", ", &AshScylla.Identifier.quote_name/1)})"

        [] ->
          ""
      end

    all_definitions =
      if pk_clause == "" do
        pk_columns ++ regular_columns
      else
        pk_columns ++ regular_columns ++ [pk_clause]
      end

    "CREATE TABLE IF NOT EXISTS #{quote_ident(table_name)} (#{Enum.join(all_definitions, ", ")})"
  end

  defp render_index_cqls(_table_name, []), do: []

  defp render_index_cqls(table_name, indexes) do
    # ScyllaDB OSS doesn't support multi-column secondary indexes.
    # Generate a separate single-column index per column.
    Enum.flat_map(indexes, fn idx ->
      idx.columns
      |> Enum.map(fn col ->
        index_name =
          if idx.name do
            "#{idx.name}_#{col}"
          else
            "idx_#{String.replace(table_name, ".", "_")}_#{col}"
          end

        "CREATE INDEX IF NOT EXISTS #{index_name} ON #{quote_ident(table_name)} (#{AshScylla.Identifier.quote_name(col)})"
      end)
    end)
  end

  # Quotes a CQL identifier, handling keyspace.table format.
  defp quote_ident(name) do
    name
    |> String.split(".")
    |> Enum.map_join(".", &"\"#{&1}\"")
  end

  defp render_schema_module(module_name, domain_groups) do
    schemas_literal =
      domain_groups
      |> Enum.sort_by(fn
        {:default, _} -> ""
        {domain, _} -> Module.split(domain) |> Enum.join(".")
      end)
      |> Enum.map(fn
        {:default, resources} ->
          render_domain_schema(nil, resources)

        {domain, resources} ->
          render_domain_schema(domain, resources)
      end)
      |> join_with_comma()

    module_name_str =
      module_name
      |> Module.split()
      |> Enum.join(".")

    """
    defmodule #{module_name_str} do
      @moduledoc \"\"\"
      Schema migration generated by `mix ash_scylla.gen`.
      \"\"\"

      use AshScylla.Schema

      @impl AshScylla.Schema
      def change do
    [
    #{schemas_literal}
    ]
      end
    end
    """
  end

  defp render_domain_schema(nil, resources) do
    resources_literal =
      resources
      |> Enum.map(&render_resource_struct/1)
      |> join_with_comma()

    """
    %AshScylla.Schema{
      resources: [
    #{resources_literal}
      ]
    }
    """
  end

  defp render_domain_schema(domain, resources) do
    resources_literal =
      resources
      |> Enum.map(&render_resource_struct/1)
      |> join_with_comma()

    """
    %AshScylla.Schema{
      domain: #{Module.split(domain) |> Enum.join(".")},
      resources: [
    #{resources_literal}
      ]
    }
    """
  end

  # Joins a list of rendered strings with commas, placing the comma at the
  # end of each line rather than the start of the next.
  defp join_with_comma([]), do: ""
  defp join_with_comma([single]), do: single

  defp join_with_comma(strings) do
    strings
    |> Enum.map(&String.trim_trailing/1)
    |> Enum.map_join(",\n", fn s -> s end)
  end

  defp render_resource_struct(resource) do
    resource_name = resource |> Module.split() |> List.last() |> String.downcase()
    table_name = resolve_table_name(resource)

    statements =
      render_resource_statements(
        table_name,
        Ash.Resource.Info.attributes(resource),
        AshScylla.DataLayer.Dsl.secondary_indexes(resource)
      )

    statements_literal =
      statements
      |> Enum.map_join(",\n", &"      \"#{escape_string(&1)}\"")

    """
    %AshScylla.Schema.Resource{
      name: :#{resource_name},
      statements: [
    #{statements_literal}
      ]
    }
    """
  end

  defp escape_string(s) do
    s |> String.replace("\\", "\\\\") |> String.replace("\"", "\\\"")
  end
end
