# Copyright [2024] AshScylla Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defmodule AshScylla.Schema do
  @moduledoc """
  Behaviour for schema migration modules loaded from `priv/migrations`.

  Schema files are optional Elixir modules that return CQL statements from
  `change/0`. They can return raw CQL strings or structured `%AshScylla.Schema{}
  entries organised by domain and resource.

  ## Struct-based schema (generated by `mix ash_scylla.gen`)

      defmodule MyApp.Migrations.Schema20260615155440 do
        use AshScylla.Schema

        def change do
          [
            %AshScylla.Schema{
              domain: MyApp.Domain,
              resources: [
                %AshScylla.Schema.Resource{
                  name: :users,
                  statements: [
                    "CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, name TEXT)",
                    "CREATE INDEX IF NOT EXISTS idx_users_email ON users (email)"
                  ]
                }
              ]
            }
          ]
        end
      end

  ## Flat CQL list (hand-written)

      defmodule MyApp.Migrations.AddUserTable do
        use AshScylla.Schema

        def change do
          [
            "CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, name TEXT)"
          ]
        end
      end
  """

  @type cql :: String.t()

  @type resource :: %__MODULE__.Resource{
            name: atom(),
            statements: [cql()]
          }

  @type t :: %__MODULE__{
          domain: module(),
          resources: [resource()]
        }

  defstruct [:domain, resources: []]

  defmodule Resource do
    @moduledoc """
    Struct representing a single resource's schema statements.
    """
    @type t :: %__MODULE__{
            name: atom(),
            statements: [String.t()]
          }

    defstruct [:name, statements: []]
  end

  @callback change() :: [cql() | t()]

  @doc false
  defmacro __using__(_opts) do
    quote do
      @behaviour AshScylla.Schema

      @doc false
      def change, do: []

      defoverridable change: 0
    end
  end

  @doc """
  Flattens a `change/0` result (mix of CQL strings and Schema structs)
  into a flat list of CQL strings.
  """
  @spec flatten([cql() | t()]) :: [cql()]
  def flatten(change_result) do
    Enum.flat_map(change_result, fn
      %__MODULE__{resources: resources} ->
        Enum.flat_map(resources, fn
          %__MODULE__.Resource{statements: stmts} -> stmts
        end)

      stmt when is_binary(stmt) ->
        [stmt]
    end)
  end
end
