defmodule AshScylla.Migrations.DiffHash2 do
  @moduledoc """
  Schema migration generated by `mix ash_scylla.gen`.
  """

  use AshScylla.Schema

  @impl AshScylla.Schema
  def change do
[
%AshScylla.Schema{
  domain: AshScylla.TestDomain,
  resources: [
%AshScylla.Schema.Resource{
  name: :testresourcewithindexes,
  statements: [
      "CREATE TABLE IF NOT EXISTS \"ash_scylla_test\".\"test_users\" (id UUID, name TEXT, email TEXT, status TEXT, age BIGINT, created_at TIMESTAMP, PRIMARY KEY (id))",
      "CREATE INDEX IF NOT EXISTS idx_user_status_status ON \"ash_scylla_test\".\"test_users\" (status)",
      "CREATE INDEX IF NOT EXISTS idx_ash_scylla_test_test_users_name ON \"ash_scylla_test\".\"test_users\" (name)",
      "CREATE INDEX IF NOT EXISTS idx_ash_scylla_test_test_users_age ON \"ash_scylla_test\".\"test_users\" (age)",
      "CREATE INDEX IF NOT EXISTS idx_ash_scylla_test_test_users_email ON \"ash_scylla_test\".\"test_users\" (email)"
  ]
}

  ]
}

]
  end
end
