defmodule AshScylla.Migrations.NoChange1 do
  @moduledoc """
  Schema migration generated by `mix ash_scylla.gen`.
  """

  use AshScylla.Schema

  @impl AshScylla.Schema
  def change do
[
%AshScylla.Schema{
  domain: AshScylla.TestDomain,
  resources: [
%AshScylla.Schema.Resource{
  name: :testresource,
  statements: [
      "CREATE TABLE IF NOT EXISTS \"ash_scylla_test\".\"test_resource\" (id UUID, name TEXT, email TEXT, age BIGINT, password_hash TEXT, org_id UUID, created_at TIMESTAMP, updated_at TIMESTAMP, PRIMARY KEY (id))",
      "CREATE INDEX IF NOT EXISTS idx_ash_scylla_test_test_resource_email ON \"ash_scylla_test\".\"test_resource\" (email)",
      "CREATE INDEX IF NOT EXISTS idx_ash_scylla_test_test_resource_name ON \"ash_scylla_test\".\"test_resource\" (name)"
  ]
}

  ]
}

]
  end
end
