defmodule Elixir.AshScylla.Migrations.TestResourceCompositePK do
  @moduledoc ""
  Migration for TestResourceCompositePK.

  This file was autogenerated with `mix ash.codegen`
  ""

  use AshScylla.Schema

  @impl AshScylla.Schema
  def change do
[
  "CREATE TABLE IF NOT EXISTS \"ash_scylla_test\".\"test_composite_pk\" (
  id UUID,
  group_id UUID,
  group_type TEXT,
  from_user_id UUID,
  content TEXT,
  order BIGINT,
  deleted BOOLEAN,
  inserted_at TIMESTAMP,
  updated_at TIMESTAMP,
  PRIMARY KEY (id, group_id)
) WITH CLUSTERING ORDER BY (group_id DESC)
",
  "CREATE INDEX IF NOT EXISTS idx_test_composite_pk_group_id ON ash_scylla_test.test_composite_pk (group_id)"
]
  end
end
