defmodule AshScylla.Migrations.CompositePKSchema do
  @moduledoc """
  Schema migration generated by `mix ash_scylla.gen`.
  """

  use AshScylla.Schema

  @impl AshScylla.Schema
  def change do
[
%AshScylla.Schema{
  domain: AshScylla.TestDomain,
  resources: [
%AshScylla.Schema.Resource{
  name: :testresourcecompositepk,
  statements: [
      "CREATE TABLE IF NOT EXISTS "ash_scylla_test".test_composite_pk (id UUID, group_id UUID, group_type TEXT, from_user_id UUID, content TEXT, order BIGINT, deleted BOOLEAN, inserted_at TIMESTAMP, updated_at TIMESTAMP, PRIMARY KEY (id, group_id))",
      "CREATE INDEX IF NOT EXISTS idx_"ash_scylla_test".test_composite_pk_group_id ON "ash_scylla_test".test_composite_pk (group_id)"
  ]
}

  ]
}

]
  end
end
