defmodule AshScylla.Migrations.FileCount2 do
  @moduledoc """
  Schema migration generated by `mix ash_scylla.gen`.
  """

  use AshScylla.Schema

  @impl AshScylla.Schema
  def change do
[
%AshScylla.Schema{
  domain: AshScylla.TestDomain,
  resources: [
%AshScylla.Schema.Resource{
  name: :testresource,
  statements: [
      "CREATE TABLE IF NOT EXISTS test_resource (id UUID PRIMARY KEY, name TEXT, email TEXT, age TEXT, password_hash TEXT, org_id TEXT, created_at TEXT, updated_at TEXT)",
      "CREATE INDEX IF NOT EXISTS idx_test_resource_name ON test_resource (name)",
      "CREATE INDEX IF NOT EXISTS idx_test_resource_email ON test_resource (email)"
  ]
}

  ]
}

]
  end
end
