defmodule AshScylla.Migrations.Partial2 do
  @moduledoc """
  Schema migration generated by `mix ash_scylla.gen`.
  """

  use AshScylla.Schema

  @impl AshScylla.Schema
  def change do
[
%AshScylla.Schema{
  domain: AshScylla.TestDomain,
  resources: [
%AshScylla.Schema.Resource{
  name: :testresourcewithindexes,
  statements: [
      "CREATE TABLE IF NOT EXISTS test_users (id UUID, name TEXT, email TEXT, status TEXT, age BIGINT, created_at TIMESTAMP, PRIMARY KEY (id))",
      "CREATE INDEX IF NOT EXISTS idx_user_status_status ON test_users (status)",
      "CREATE INDEX IF NOT EXISTS idx_test_users_name ON test_users (name)",
      "CREATE INDEX IF NOT EXISTS idx_test_users_age ON test_users (age)",
      "CREATE INDEX IF NOT EXISTS idx_test_users_email ON test_users (email)"
  ]
}

  ]
}

]
  end
end
